// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 21/7/2025, 2:47:13 pm
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/Hp/Desktop/vue-firebase-quiz-app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Hp/Desktop/vue-firebase-quiz-app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Hp/Desktop/vue-firebase-quiz-app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Hp/Desktop/vue-firebase-quiz-app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Hp/Desktop/vue-firebase-quiz-app/plugins/**/*.{js,ts,mjs}","C:/Users/Hp/Desktop/vue-firebase-quiz-app/composables/**/*.{js,ts,mjs}","C:/Users/Hp/Desktop/vue-firebase-quiz-app/utils/**/*.{js,ts,mjs}","C:/Users/Hp/Desktop/vue-firebase-quiz-app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Hp/Desktop/vue-firebase-quiz-app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Hp/Desktop/vue-firebase-quiz-app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Hp/Desktop/vue-firebase-quiz-app/app.config.{js,ts,mjs}","C:/Users/Hp/Desktop/vue-firebase-quiz-app/app/spa-loading-template.html"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;